# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_stuhome(object):
    def setupUi(self, stuhome):
        stuhome.setObjectName("stuhome")
        stuhome.resize(840, 499)
        stuhome.setMinimumSize(QtCore.QSize(840, 499))
        stuhome.setMaximumSize(QtCore.QSize(840, 499))
        self.treeWidget = QtWidgets.QTreeWidget(stuhome)
        self.treeWidget.setGeometry(QtCore.QRect(0, 0, 201, 131))
        self.treeWidget.setStyleSheet("QHeaderView::section { \n"
"    height:25px;\n"
"    color:write;\n"
"    background:#6495ed;\n"
"    color: rgb(255, 255, 255);\n"
"    border-left:0px solid gray; \n"
"    border-right:1px solid gray; \n"
"    border-top:0px solid gray; \n"
"    border-bottom:0px solid gray;\n"
"}\n"
"\n"
"QTreeView {\n"
"    border:none;\n"
"    background: #6495ed;\n"
"}\n"
"QTreeView::item {\n"
"    height: 25px;\n"
"    border: none;\n"
"    color: white;\n"
"}\n"
"\n"
"QTreeView::branch:closed:has-children{\n"
"    \n"
"    \n"
"    image: url(:/icon/images/右.png);\n"
"}\n"
"QTreeView::branch:open:has-children{\n"
"    image: url(:/icon/images/下.png);\n"
"}")
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setTextAlignment(0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.treeWidget.headerItem().setFont(0, font)
        self.treeWidget.headerItem().setBackground(0, QtGui.QColor(132, 161, 197))
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item_0.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        self.treeWidget_2 = QtWidgets.QTreeWidget(stuhome)
        self.treeWidget_2.setGeometry(QtCore.QRect(0, 130, 201, 151))
        self.treeWidget_2.setStyleSheet("QHeaderView::section { \n"
"    height:25px;\n"
"    color:white;\n"
"    background:#6495ed;\n"
"    border-left:0px solid gray; \n"
"    border-right:1px solid gray; \n"
"    border-top:0px solid gray; \n"
"    border-bottom:0px solid gray;\n"
"}\n"
"\n"
"QTreeView {\n"
"    border:none;\n"
"    background: #6495ed;\n"
"}\n"
"QTreeView::item {\n"
"    height: 25px;\n"
"    border: none;\n"
"    color: white;\n"
"}\n"
"\n"
"QTreeView::branch:closed:has-children{\n"
"    image: url(:/icon/images/右.png);\n"
"}\n"
"QTreeView::branch:open:has-children{\n"
"    image: url(:/icon/images/下.png);\n"
"}")
        self.treeWidget_2.setLineWidth(1)
        self.treeWidget_2.setAutoExpandDelay(40)
        self.treeWidget_2.setIndentation(25)
        self.treeWidget_2.setUniformRowHeights(False)
        self.treeWidget_2.setObjectName("treeWidget_2")
        self.treeWidget_2.headerItem().setTextAlignment(0, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.treeWidget_2.headerItem().setFont(0, font)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_2)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item_0.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        self.treeWidget_2.header().setDefaultSectionSize(134)
        self.treeWidget_2.header().setMinimumSectionSize(37)
        self.treeWidget_3 = QtWidgets.QTreeWidget(stuhome)
        self.treeWidget_3.setGeometry(QtCore.QRect(0, 280, 201, 221))
        self.treeWidget_3.setStyleSheet("QHeaderView::section { \n"
"    height:25px;\n"
"    color:white;\n"
"    background:#6495ed;\n"
"    border-left:0px solid gray; \n"
"    border-right:1px solid gray; \n"
"    border-top:0px solid gray; \n"
"    border-bottom:0px solid gray;\n"
"}\n"
"\n"
"QTreeView {\n"
"    border:none;\n"
"    background: #6495ed;\n"
"}\n"
"QTreeView::item {\n"
"    height: 25px;\n"
"    border: none;\n"
"    color: white;\n"
"}\n"
"\n"
"QTreeView::branch:closed:has-children{\n"
"    image: url(:/icon/images/右.png);\n"
"}\n"
"QTreeView::branch:open:has-children{\n"
"    image: url(:/icon/images/下.png);\n"
"}")
        self.treeWidget_3.setLineWidth(1)
        self.treeWidget_3.setAutoExpandDelay(40)
        self.treeWidget_3.setIndentation(25)
        self.treeWidget_3.setUniformRowHeights(False)
        self.treeWidget_3.setObjectName("treeWidget_3")
        self.treeWidget_3.headerItem().setTextAlignment(0, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.treeWidget_3.headerItem().setFont(0, font)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_3)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item_0.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        self.treeWidget_3.header().setDefaultSectionSize(134)
        self.treeWidget_3.header().setMinimumSectionSize(37)
        self.listView_2 = QtWidgets.QListView(stuhome)
        self.listView_2.setGeometry(QtCore.QRect(200, 0, 641, 501))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.listView_2.setFont(font)
        self.listView_2.setStyleSheet("background-color: rgb(249, 249, 249);")
        self.listView_2.setObjectName("listView_2")
        self.listView_3 = QtWidgets.QListView(stuhome)
        self.listView_3.setGeometry(QtCore.QRect(210, 80, 161, 91))
        self.listView_3.setStyleSheet("background-color: rgb(100, 149, 237);\n"
"border-radius:10px;")
        self.listView_3.setObjectName("listView_3")
        self.label = QtWidgets.QLabel(stuhome)
        self.label.setGeometry(QtCore.QRect(230, 20, 151, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(stuhome)
        self.label_2.setGeometry(QtCore.QRect(0, 270, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(stuhome)
        self.label_3.setGeometry(QtCore.QRect(0, 120, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(stuhome)
        self.label_4.setGeometry(QtCore.QRect(220, 90, 51, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_4.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.listView_4 = QtWidgets.QListView(stuhome)
        self.listView_4.setGeometry(QtCore.QRect(400, 80, 161, 91))
        self.listView_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:0px;\n"
"border-radius:10px;")
        self.listView_4.setObjectName("listView_4")
        self.name = QtWidgets.QLabel(stuhome)
        self.name.setGeometry(QtCore.QRect(250, 130, 111, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.name.setFont(font)
        self.name.setText("")
        self.name.setObjectName("name")
        self.listView_5 = QtWidgets.QListView(stuhome)
        self.listView_5.setGeometry(QtCore.QRect(400, 200, 161, 91))
        self.listView_5.setStyleSheet("background-color: rgb(100, 149, 237);\n"
"border-radius:10px;")
        self.listView_5.setObjectName("listView_5")
        self.listView_6 = QtWidgets.QListView(stuhome)
        self.listView_6.setGeometry(QtCore.QRect(210, 200, 161, 91))
        self.listView_6.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:0px;\n"
"border-radius:10px;")
        self.listView_6.setObjectName("listView_6")
        self.listView_7 = QtWidgets.QListView(stuhome)
        self.listView_7.setGeometry(QtCore.QRect(400, 320, 161, 91))
        self.listView_7.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:0px;\n"
"border-radius:10px;")
        self.listView_7.setObjectName("listView_7")
        self.listView_8 = QtWidgets.QListView(stuhome)
        self.listView_8.setGeometry(QtCore.QRect(210, 320, 161, 91))
        self.listView_8.setStyleSheet("background-color: rgb(100, 149, 237);\n"
"border-radius:10px;")
        self.listView_8.setObjectName("listView_8")
        self.label_6 = QtWidgets.QLabel(stuhome)
        self.label_6.setGeometry(QtCore.QRect(410, 210, 51, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_6.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(stuhome)
        self.label_7.setGeometry(QtCore.QRect(230, 330, 51, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_7.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(stuhome)
        self.label_8.setGeometry(QtCore.QRect(410, 90, 51, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(100, 149, 237))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 149, 237))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_8.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(stuhome)
        self.label_9.setGeometry(QtCore.QRect(230, 210, 51, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(100, 149, 237))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 149, 237))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_9.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(stuhome)
        self.label_10.setGeometry(QtCore.QRect(410, 330, 91, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(100, 149, 237))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 149, 237))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_10.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.id = QtWidgets.QLabel(stuhome)
        self.id.setGeometry(QtCore.QRect(440, 130, 111, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.id.setFont(font)
        self.id.setText("")
        self.id.setObjectName("id")
        self.age = QtWidgets.QLabel(stuhome)
        self.age.setGeometry(QtCore.QRect(250, 250, 111, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.age.setFont(font)
        self.age.setText("")
        self.age.setObjectName("age")
        self.sex = QtWidgets.QLabel(stuhome)
        self.sex.setGeometry(QtCore.QRect(440, 250, 111, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sex.setFont(font)
        self.sex.setText("")
        self.sex.setObjectName("sex")
        self.class_2 = QtWidgets.QLabel(stuhome)
        self.class_2.setGeometry(QtCore.QRect(250, 370, 111, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.class_2.setFont(font)
        self.class_2.setText("")
        self.class_2.setObjectName("class_2")
        self.phone = QtWidgets.QLabel(stuhome)
        self.phone.setGeometry(QtCore.QRect(440, 370, 111, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.phone.setFont(font)
        self.phone.setText("")
        self.phone.setObjectName("phone")
        self.listView_2.raise_()
        self.treeWidget.raise_()
        self.treeWidget_2.raise_()
        self.treeWidget_3.raise_()
        self.listView_3.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.listView_4.raise_()
        self.name.raise_()
        self.listView_5.raise_()
        self.listView_6.raise_()
        self.listView_7.raise_()
        self.listView_8.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.id.raise_()
        self.age.raise_()
        self.sex.raise_()
        self.class_2.raise_()
        self.phone.raise_()

        self.retranslateUi(stuhome)
        QtCore.QMetaObject.connectSlotsByName(stuhome)

    def retranslateUi(self, stuhome):
        _translate = QtCore.QCoreApplication.translate
        stuhome.setWindowTitle(_translate("stuhome", "学生管理"))
        self.treeWidget.headerItem().setText(0, _translate("stuhome", "学生系统"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("stuhome", "系统管理"))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("stuhome", "退出系统"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.treeWidget_2.headerItem().setText(0, _translate("stuhome", "选课系统"))
        __sortingEnabled = self.treeWidget_2.isSortingEnabled()
        self.treeWidget_2.setSortingEnabled(False)
        self.treeWidget_2.topLevelItem(0).setText(0, _translate("stuhome", "选课管理"))
        self.treeWidget_2.topLevelItem(0).child(0).setText(0, _translate("stuhome", "选择课程"))
        self.treeWidget_2.topLevelItem(0).child(1).setText(0, _translate("stuhome", "查询课程"))
        self.treeWidget_2.topLevelItem(0).child(2).setText(0, _translate("stuhome", "显示课表"))
        self.treeWidget_2.setSortingEnabled(__sortingEnabled)
        self.treeWidget_3.headerItem().setText(0, _translate("stuhome", "成绩系统"))
        __sortingEnabled = self.treeWidget_3.isSortingEnabled()
        self.treeWidget_3.setSortingEnabled(False)
        self.treeWidget_3.topLevelItem(0).setText(0, _translate("stuhome", "成绩管理"))
        self.treeWidget_3.topLevelItem(0).child(0).setText(0, _translate("stuhome", "我的成绩"))
        self.treeWidget_3.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("stuhome", "~~首页~~"))
        self.label_2.setText(_translate("stuhome", "-------------------------"))
        self.label_3.setText(_translate("stuhome", "-------------------------"))
        self.label_4.setText(_translate("stuhome", "姓名"))
        self.label_6.setText(_translate("stuhome", "性别"))
        self.label_7.setText(_translate("stuhome", "班级"))
        self.label_8.setText(_translate("stuhome", "学号"))
        self.label_9.setText(_translate("stuhome", "年龄"))
        self.label_10.setText(_translate("stuhome", "联系方式"))
import home_rc
