# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_stuhome(object):
    def setupUi(self, stuhome):
        stuhome.setObjectName("stuhome")
        stuhome.resize(840, 499)
        stuhome.setMinimumSize(QtCore.QSize(840, 499))
        stuhome.setMaximumSize(QtCore.QSize(840, 499))
        self.stackedWidget = QtWidgets.QStackedWidget(stuhome)
        self.stackedWidget.setGeometry(QtCore.QRect(200, 0, 641, 501))
        self.stackedWidget.setStyleSheet("background-color: rgb(249, 249, 249);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.listView_4 = QtWidgets.QListView(self.page)
        self.listView_4.setGeometry(QtCore.QRect(200, 110, 161, 91))
        self.listView_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:0px;\n"
"border-radius:10px;")
        self.listView_4.setObjectName("listView_4")
        self.name = QtWidgets.QLabel(self.page)
        self.name.setGeometry(QtCore.QRect(50, 160, 111, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.name.setFont(font)
        self.name.setStyleSheet("background-color: rgb(100, 149, 237);")
        self.name.setText("")
        self.name.setObjectName("name")
        self.class_2 = QtWidgets.QLabel(self.page)
        self.class_2.setGeometry(QtCore.QRect(50, 400, 111, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.class_2.setFont(font)
        self.class_2.setStyleSheet("background-color: rgb(100, 149, 237);")
        self.class_2.setText("")
        self.class_2.setObjectName("class_2")
        self.label_8 = QtWidgets.QLabel(self.page)
        self.label_8.setGeometry(QtCore.QRect(210, 120, 51, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(100, 149, 237))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 149, 237))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_8.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.listView_7 = QtWidgets.QListView(self.page)
        self.listView_7.setGeometry(QtCore.QRect(200, 350, 161, 91))
        self.listView_7.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:0px;\n"
"border-radius:10px;")
        self.listView_7.setObjectName("listView_7")
        self.label_10 = QtWidgets.QLabel(self.page)
        self.label_10.setGeometry(QtCore.QRect(210, 360, 91, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(100, 149, 237))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 149, 237))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_10.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_10.setObjectName("label_10")
        self.age = QtWidgets.QLabel(self.page)
        self.age.setGeometry(QtCore.QRect(50, 280, 111, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.age.setFont(font)
        self.age.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.age.setText("")
        self.age.setObjectName("age")
        self.label_9 = QtWidgets.QLabel(self.page)
        self.label_9.setGeometry(QtCore.QRect(30, 240, 61, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(100, 149, 237))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 149, 237))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_9.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")
        self.listView_6 = QtWidgets.QListView(self.page)
        self.listView_6.setGeometry(QtCore.QRect(10, 230, 161, 91))
        self.listView_6.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:0px;\n"
"border-radius:10px;")
        self.listView_6.setObjectName("listView_6")
        self.sex = QtWidgets.QLabel(self.page)
        self.sex.setGeometry(QtCore.QRect(240, 280, 111, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sex.setFont(font)
        self.sex.setStyleSheet("background-color: rgb(100, 149, 237);")
        self.sex.setText("")
        self.sex.setObjectName("sex")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(30, 30, 151, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_6 = QtWidgets.QLabel(self.page)
        self.label_6.setGeometry(QtCore.QRect(210, 240, 51, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 149, 237))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 149, 237))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 149, 237))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 149, 237))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 149, 237))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 149, 237))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 149, 237))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 149, 237))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 149, 237))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_6.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color: rgb(100, 149, 237);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.page)
        self.label_7.setGeometry(QtCore.QRect(20, 360, 51, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 149, 237))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 149, 237))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 149, 237))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 149, 237))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 149, 237))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 149, 237))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 149, 237))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 149, 237))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 149, 237))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_7.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color: rgb(100, 149, 237);")
        self.label_7.setObjectName("label_7")
        self.label_4 = QtWidgets.QLabel(self.page)
        self.label_4.setGeometry(QtCore.QRect(20, 120, 51, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 149, 237))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 149, 237))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 149, 237))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 149, 237))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 149, 237))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 149, 237))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 149, 237))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 149, 237))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 149, 237))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_4.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(100, 149, 237);")
        self.label_4.setObjectName("label_4")
        self.listView_8 = QtWidgets.QListView(self.page)
        self.listView_8.setGeometry(QtCore.QRect(10, 350, 161, 91))
        self.listView_8.setStyleSheet("background-color: rgb(100, 149, 237);\n"
"border-radius:10px;")
        self.listView_8.setObjectName("listView_8")
        self.id = QtWidgets.QLabel(self.page)
        self.id.setGeometry(QtCore.QRect(240, 160, 111, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.id.setFont(font)
        self.id.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.id.setText("")
        self.id.setObjectName("id")
        self.listView_5 = QtWidgets.QListView(self.page)
        self.listView_5.setGeometry(QtCore.QRect(200, 230, 161, 91))
        self.listView_5.setStyleSheet("background-color: rgb(100, 149, 237);\n"
"border-radius:10px;")
        self.listView_5.setObjectName("listView_5")
        self.phone = QtWidgets.QLabel(self.page)
        self.phone.setGeometry(QtCore.QRect(240, 400, 111, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.phone.setFont(font)
        self.phone.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.phone.setText("")
        self.phone.setObjectName("phone")
        self.listView_3 = QtWidgets.QListView(self.page)
        self.listView_3.setGeometry(QtCore.QRect(10, 110, 161, 91))
        self.listView_3.setStyleSheet("background-color: rgb(100, 149, 237);\n"
"border-radius:10px;")
        self.listView_3.setObjectName("listView_3")
        self.listView_4.raise_()
        self.label_8.raise_()
        self.listView_7.raise_()
        self.label_10.raise_()
        self.listView_6.raise_()
        self.label.raise_()
        self.listView_8.raise_()
        self.id.raise_()
        self.listView_5.raise_()
        self.listView_3.raise_()
        self.label_9.raise_()
        self.label_7.raise_()
        self.label_6.raise_()
        self.label_4.raise_()
        self.age.raise_()
        self.class_2.raise_()
        self.name.raise_()
        self.phone.raise_()
        self.sex.raise_()
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_5 = QtWidgets.QLabel(self.page_2)
        self.label_5.setGeometry(QtCore.QRect(20, 30, 201, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.listView = QtWidgets.QListView(self.page_2)
        self.listView.setGeometry(QtCore.QRect(20, 120, 521, 181))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(10)
        self.listView.setFont(font)
        self.listView.setObjectName("listView")
        self.stackedWidget.addWidget(self.page_2)
        self.stackedWidget_2 = QtWidgets.QStackedWidget(stuhome)
        self.stackedWidget_2.setGeometry(QtCore.QRect(0, 0, 201, 501))
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.ScoreManager = QtWidgets.QTreeWidget(self.page_3)
        self.ScoreManager.setGeometry(QtCore.QRect(0, 310, 201, 191))
        self.ScoreManager.setStyleSheet("QHeaderView::section { \n"
"    height:25px;\n"
"    color:white;\n"
"    background:#6495ed;\n"
"    border-left:0px solid gray; \n"
"    border-right:1px solid gray; \n"
"    border-top:0px solid gray; \n"
"    border-bottom:0px solid gray;\n"
"}\n"
"\n"
"QTreeView {\n"
"    border:none;\n"
"    background: #6495ed;\n"
"}\n"
"QTreeView::item {\n"
"    height: 25px;\n"
"    border: none;\n"
"    color: white;\n"
"}\n"
"\n"
"QTreeView::branch:closed:has-children{\n"
"    image: url(:/icon/images/右.png);\n"
"}\n"
"QTreeView::branch:open:has-children{\n"
"    image: url(:/icon/images/下.png);\n"
"}")
        self.ScoreManager.setLineWidth(1)
        self.ScoreManager.setAutoExpandDelay(40)
        self.ScoreManager.setIndentation(25)
        self.ScoreManager.setUniformRowHeights(False)
        self.ScoreManager.setObjectName("ScoreManager")
        self.ScoreManager.headerItem().setTextAlignment(0, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.ScoreManager.headerItem().setFont(0, font)
        item_0 = QtWidgets.QTreeWidgetItem(self.ScoreManager)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item_0.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        self.ScoreManager.header().setDefaultSectionSize(134)
        self.ScoreManager.header().setMinimumSectionSize(37)
        self.SystemSet = QtWidgets.QTreeWidget(self.page_3)
        self.SystemSet.setGeometry(QtCore.QRect(0, 0, 201, 131))
        self.SystemSet.setStyleSheet("QHeaderView::section { \n"
"    height:25px;\n"
"    color:write;\n"
"    background:#6495ed;\n"
"    color: rgb(255, 255, 255);\n"
"    border-left:0px solid gray; \n"
"    border-right:1px solid gray; \n"
"    border-top:0px solid gray; \n"
"    border-bottom:0px solid gray;\n"
"}\n"
"\n"
"QTreeView {\n"
"    border:none;\n"
"    background: #6495ed;\n"
"}\n"
"QTreeView::item {\n"
"    height: 25px;\n"
"    border: none;\n"
"    color: white;\n"
"}\n"
"\n"
"QTreeView::branch:closed:has-children{\n"
"    \n"
"    \n"
"    image: url(:/icon/images/右.png);\n"
"}\n"
"QTreeView::branch:open:has-children{\n"
"    image: url(:/icon/images/下.png);\n"
"}")
        self.SystemSet.setObjectName("SystemSet")
        self.SystemSet.headerItem().setTextAlignment(0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.SystemSet.headerItem().setFont(0, font)
        self.SystemSet.headerItem().setBackground(0, QtGui.QColor(132, 161, 197))
        item_0 = QtWidgets.QTreeWidgetItem(self.SystemSet)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item_0.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        self.CourseSelection = QtWidgets.QTreeWidget(self.page_3)
        self.CourseSelection.setGeometry(QtCore.QRect(0, 130, 201, 181))
        self.CourseSelection.setStyleSheet("QHeaderView::section { \n"
"    height:25px;\n"
"    color:white;\n"
"    background:#6495ed;\n"
"    border-left:0px solid gray; \n"
"    border-right:1px solid gray; \n"
"    border-top:0px solid gray; \n"
"    border-bottom:0px solid gray;\n"
"}\n"
"\n"
"QTreeView {\n"
"    border:none;\n"
"    background: #6495ed;\n"
"}\n"
"QTreeView::item {\n"
"    height: 25px;\n"
"    border: none;\n"
"    color: white;\n"
"}\n"
"\n"
"QTreeView::branch:closed:has-children{\n"
"    image: url(:/icon/images/右.png);\n"
"}\n"
"QTreeView::branch:open:has-children{\n"
"    image: url(:/icon/images/下.png);\n"
"}")
        self.CourseSelection.setLineWidth(1)
        self.CourseSelection.setAutoExpandDelay(40)
        self.CourseSelection.setIndentation(25)
        self.CourseSelection.setUniformRowHeights(False)
        self.CourseSelection.setObjectName("CourseSelection")
        self.CourseSelection.headerItem().setTextAlignment(0, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.CourseSelection.headerItem().setFont(0, font)
        item_0 = QtWidgets.QTreeWidgetItem(self.CourseSelection)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item_0.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        self.CourseSelection.header().setDefaultSectionSize(134)
        self.CourseSelection.header().setMinimumSectionSize(37)
        self.label_3 = QtWidgets.QLabel(self.page_3)
        self.label_3.setGeometry(QtCore.QRect(0, 120, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.page_3)
        self.label_2.setGeometry(QtCore.QRect(0, 300, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.stackedWidget_2.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.SystemSet_2 = QtWidgets.QTreeWidget(self.page_4)
        self.SystemSet_2.setGeometry(QtCore.QRect(0, 0, 201, 131))
        self.SystemSet_2.setStyleSheet("QHeaderView::section { \n"
"    height:25px;\n"
"    color:write;\n"
"    background:#6495ed;\n"
"    color: rgb(255, 255, 255);\n"
"    border-left:0px solid gray; \n"
"    border-right:1px solid gray; \n"
"    border-top:0px solid gray; \n"
"    border-bottom:0px solid gray;\n"
"}\n"
"\n"
"QTreeView {\n"
"    border:none;\n"
"    background: #6495ed;\n"
"}\n"
"QTreeView::item {\n"
"    height: 25px;\n"
"    border: none;\n"
"    color: white;\n"
"}\n"
"\n"
"QTreeView::branch:closed:has-children{\n"
"    \n"
"    \n"
"    image: url(:/icon/images/右.png);\n"
"}\n"
"QTreeView::branch:open:has-children{\n"
"    image: url(:/icon/images/下.png);\n"
"}")
        self.SystemSet_2.setObjectName("SystemSet_2")
        self.SystemSet_2.headerItem().setTextAlignment(0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.SystemSet_2.headerItem().setFont(0, font)
        self.SystemSet_2.headerItem().setBackground(0, QtGui.QColor(132, 161, 197))
        item_0 = QtWidgets.QTreeWidgetItem(self.SystemSet_2)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item_0.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        self.ScoreManager_2 = QtWidgets.QTreeWidget(self.page_4)
        self.ScoreManager_2.setGeometry(QtCore.QRect(0, 310, 201, 191))
        self.ScoreManager_2.setStyleSheet("QHeaderView::section { \n"
"    height:25px;\n"
"    color:white;\n"
"    background:#6495ed;\n"
"    border-left:0px solid gray; \n"
"    border-right:1px solid gray; \n"
"    border-top:0px solid gray; \n"
"    border-bottom:0px solid gray;\n"
"}\n"
"\n"
"QTreeView {\n"
"    border:none;\n"
"    background: #6495ed;\n"
"}\n"
"QTreeView::item {\n"
"    height: 25px;\n"
"    border: none;\n"
"    color: white;\n"
"}\n"
"\n"
"QTreeView::branch:closed:has-children{\n"
"    image: url(:/icon/images/右.png);\n"
"}\n"
"QTreeView::branch:open:has-children{\n"
"    image: url(:/icon/images/下.png);\n"
"}")
        self.ScoreManager_2.setLineWidth(1)
        self.ScoreManager_2.setAutoExpandDelay(40)
        self.ScoreManager_2.setIndentation(25)
        self.ScoreManager_2.setUniformRowHeights(False)
        self.ScoreManager_2.setObjectName("ScoreManager_2")
        self.ScoreManager_2.headerItem().setTextAlignment(0, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.ScoreManager_2.headerItem().setFont(0, font)
        item_0 = QtWidgets.QTreeWidgetItem(self.ScoreManager_2)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item_0.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        self.ScoreManager_2.header().setDefaultSectionSize(134)
        self.ScoreManager_2.header().setMinimumSectionSize(37)
        self.CourseSelection_2 = QtWidgets.QTreeWidget(self.page_4)
        self.CourseSelection_2.setGeometry(QtCore.QRect(0, 130, 201, 181))
        self.CourseSelection_2.setStyleSheet("QHeaderView::section { \n"
"    height:25px;\n"
"    color:white;\n"
"    background:#6495ed;\n"
"    border-left:0px solid gray; \n"
"    border-right:1px solid gray; \n"
"    border-top:0px solid gray; \n"
"    border-bottom:0px solid gray;\n"
"}\n"
"\n"
"QTreeView {\n"
"    border:none;\n"
"    background: #6495ed;\n"
"}\n"
"QTreeView::item {\n"
"    height: 25px;\n"
"    border: none;\n"
"    color: white;\n"
"}\n"
"\n"
"QTreeView::branch:closed:has-children{\n"
"    image: url(:/icon/images/右.png);\n"
"}\n"
"QTreeView::branch:open:has-children{\n"
"    image: url(:/icon/images/下.png);\n"
"}")
        self.CourseSelection_2.setLineWidth(1)
        self.CourseSelection_2.setAutoExpandDelay(40)
        self.CourseSelection_2.setIndentation(25)
        self.CourseSelection_2.setUniformRowHeights(False)
        self.CourseSelection_2.setObjectName("CourseSelection_2")
        self.CourseSelection_2.headerItem().setTextAlignment(0, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.CourseSelection_2.headerItem().setFont(0, font)
        item_0 = QtWidgets.QTreeWidgetItem(self.CourseSelection_2)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item_0.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        self.CourseSelection_2.header().setDefaultSectionSize(134)
        self.CourseSelection_2.header().setMinimumSectionSize(37)
        self.label_17 = QtWidgets.QLabel(self.page_4)
        self.label_17.setGeometry(QtCore.QRect(0, 120, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.page_4)
        self.label_18.setGeometry(QtCore.QRect(0, 300, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.stackedWidget_2.addWidget(self.page_4)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.SystemSet_3 = QtWidgets.QTreeWidget(self.page_7)
        self.SystemSet_3.setGeometry(QtCore.QRect(0, 0, 201, 101))
        self.SystemSet_3.setStyleSheet("QHeaderView::section { \n"
"    height:25px;\n"
"    color:write;\n"
"    background:#6495ed;\n"
"    color: rgb(255, 255, 255);\n"
"    border-left:0px solid gray; \n"
"    border-right:1px solid gray; \n"
"    border-top:0px solid gray; \n"
"    border-bottom:0px solid gray;\n"
"}\n"
"\n"
"QTreeView {\n"
"    border:none;\n"
"    background: #6495ed;\n"
"}\n"
"QTreeView::item {\n"
"    height: 25px;\n"
"    border: none;\n"
"    color: white;\n"
"}\n"
"\n"
"QTreeView::branch:closed:has-children{\n"
"    \n"
"    \n"
"    image: url(:/icon/images/右.png);\n"
"}\n"
"QTreeView::branch:open:has-children{\n"
"    image: url(:/icon/images/下.png);\n"
"}")
        self.SystemSet_3.setObjectName("SystemSet_3")
        self.SystemSet_3.headerItem().setTextAlignment(0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.SystemSet_3.headerItem().setFont(0, font)
        self.SystemSet_3.headerItem().setBackground(0, QtGui.QColor(132, 161, 197))
        item_0 = QtWidgets.QTreeWidgetItem(self.SystemSet_3)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item_0.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        self.ScoreManager_3 = QtWidgets.QTreeWidget(self.page_7)
        self.ScoreManager_3.setGeometry(QtCore.QRect(0, 250, 201, 121))
        self.ScoreManager_3.setStyleSheet("QHeaderView::section { \n"
"    height:25px;\n"
"    color:white;\n"
"    background:#6495ed;\n"
"    border-left:0px solid gray; \n"
"    border-right:1px solid gray; \n"
"    border-top:0px solid gray; \n"
"    border-bottom:0px solid gray;\n"
"}\n"
"\n"
"QTreeView {\n"
"    border:none;\n"
"    background: #6495ed;\n"
"}\n"
"QTreeView::item {\n"
"    height: 25px;\n"
"    border: none;\n"
"    color: white;\n"
"}\n"
"\n"
"QTreeView::branch:closed:has-children{\n"
"    image: url(:/icon/images/右.png);\n"
"}\n"
"QTreeView::branch:open:has-children{\n"
"    image: url(:/icon/images/下.png);\n"
"}")
        self.ScoreManager_3.setLineWidth(1)
        self.ScoreManager_3.setAutoExpandDelay(40)
        self.ScoreManager_3.setIndentation(25)
        self.ScoreManager_3.setUniformRowHeights(False)
        self.ScoreManager_3.setObjectName("ScoreManager_3")
        self.ScoreManager_3.headerItem().setTextAlignment(0, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.ScoreManager_3.headerItem().setFont(0, font)
        item_0 = QtWidgets.QTreeWidgetItem(self.ScoreManager_3)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item_0.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        self.ScoreManager_3.header().setDefaultSectionSize(134)
        self.ScoreManager_3.header().setMinimumSectionSize(37)
        self.CourseSelection_3 = QtWidgets.QTreeWidget(self.page_7)
        self.CourseSelection_3.setGeometry(QtCore.QRect(0, 100, 201, 151))
        self.CourseSelection_3.setStyleSheet("QHeaderView::section { \n"
"    height:25px;\n"
"    color:white;\n"
"    background:#6495ed;\n"
"    border-left:0px solid gray; \n"
"    border-right:1px solid gray; \n"
"    border-top:0px solid gray; \n"
"    border-bottom:0px solid gray;\n"
"}\n"
"\n"
"QTreeView {\n"
"    border:none;\n"
"    background: #6495ed;\n"
"}\n"
"QTreeView::item {\n"
"    height: 25px;\n"
"    border: none;\n"
"    color: white;\n"
"}\n"
"\n"
"QTreeView::branch:closed:has-children{\n"
"    image: url(:/icon/images/右.png);\n"
"}\n"
"QTreeView::branch:open:has-children{\n"
"    image: url(:/icon/images/下.png);\n"
"}")
        self.CourseSelection_3.setLineWidth(1)
        self.CourseSelection_3.setAutoExpandDelay(40)
        self.CourseSelection_3.setIndentation(25)
        self.CourseSelection_3.setUniformRowHeights(False)
        self.CourseSelection_3.setObjectName("CourseSelection_3")
        self.CourseSelection_3.headerItem().setTextAlignment(0, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.CourseSelection_3.headerItem().setFont(0, font)
        item_0 = QtWidgets.QTreeWidgetItem(self.CourseSelection_3)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item_0.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        self.CourseSelection_3.header().setDefaultSectionSize(134)
        self.CourseSelection_3.header().setMinimumSectionSize(37)
        self.ScoreManager_4 = QtWidgets.QTreeWidget(self.page_7)
        self.ScoreManager_4.setGeometry(QtCore.QRect(0, 370, 201, 141))
        self.ScoreManager_4.setStyleSheet("QHeaderView::section { \n"
"    height:25px;\n"
"    color:white;\n"
"    background:#6495ed;\n"
"    border-left:0px solid gray; \n"
"    border-right:1px solid gray; \n"
"    border-top:0px solid gray; \n"
"    border-bottom:0px solid gray;\n"
"}\n"
"\n"
"QTreeView {\n"
"    border:none;\n"
"    background: #6495ed;\n"
"}\n"
"QTreeView::item {\n"
"    height: 25px;\n"
"    border: none;\n"
"    color: white;\n"
"}\n"
"\n"
"QTreeView::branch:closed:has-children{\n"
"    image: url(:/icon/images/右.png);\n"
"}\n"
"QTreeView::branch:open:has-children{\n"
"    image: url(:/icon/images/下.png);\n"
"}")
        self.ScoreManager_4.setLineWidth(1)
        self.ScoreManager_4.setAutoExpandDelay(40)
        self.ScoreManager_4.setIndentation(25)
        self.ScoreManager_4.setUniformRowHeights(False)
        self.ScoreManager_4.setObjectName("ScoreManager_4")
        self.ScoreManager_4.headerItem().setTextAlignment(0, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.ScoreManager_4.headerItem().setFont(0, font)
        item_0 = QtWidgets.QTreeWidgetItem(self.ScoreManager_4)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item_0.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        self.ScoreManager_4.header().setDefaultSectionSize(134)
        self.ScoreManager_4.header().setMinimumSectionSize(37)
        self.label_19 = QtWidgets.QLabel(self.page_7)
        self.label_19.setGeometry(QtCore.QRect(0, 90, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.page_7)
        self.label_20.setGeometry(QtCore.QRect(0, 240, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.page_7)
        self.label_21.setGeometry(QtCore.QRect(0, 360, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.stackedWidget_2.addWidget(self.page_7)

        self.retranslateUi(stuhome)
        self.stackedWidget.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(stuhome)

    def retranslateUi(self, stuhome):
        _translate = QtCore.QCoreApplication.translate
        stuhome.setWindowTitle(_translate("stuhome", "学生管理"))
        self.label_8.setText(_translate("stuhome", "学号"))
        self.label_10.setText(_translate("stuhome", "联系方式"))
        self.label_9.setText(_translate("stuhome", "年龄"))
        self.label.setText(_translate("stuhome", "~~首页~~"))
        self.label_6.setText(_translate("stuhome", "性别"))
        self.label_7.setText(_translate("stuhome", "班级"))
        self.label_4.setText(_translate("stuhome", "姓名"))
        self.label_5.setText(_translate("stuhome", "~~选课信息~~"))
        self.ScoreManager.headerItem().setText(0, _translate("stuhome", "成绩系统"))
        __sortingEnabled = self.ScoreManager.isSortingEnabled()
        self.ScoreManager.setSortingEnabled(False)
        self.ScoreManager.topLevelItem(0).setText(0, _translate("stuhome", "成绩管理"))
        self.ScoreManager.topLevelItem(0).child(0).setText(0, _translate("stuhome", "我的成绩"))
        self.ScoreManager.setSortingEnabled(__sortingEnabled)
        self.SystemSet.headerItem().setText(0, _translate("stuhome", "学生系统"))
        __sortingEnabled = self.SystemSet.isSortingEnabled()
        self.SystemSet.setSortingEnabled(False)
        self.SystemSet.topLevelItem(0).setText(0, _translate("stuhome", "系统管理"))
        self.SystemSet.topLevelItem(0).child(0).setText(0, _translate("stuhome", "返回首页"))
        self.SystemSet.topLevelItem(0).child(1).setText(0, _translate("stuhome", "退出系统"))
        self.SystemSet.setSortingEnabled(__sortingEnabled)
        self.CourseSelection.headerItem().setText(0, _translate("stuhome", "选课系统"))
        __sortingEnabled = self.CourseSelection.isSortingEnabled()
        self.CourseSelection.setSortingEnabled(False)
        self.CourseSelection.topLevelItem(0).setText(0, _translate("stuhome", "选课管理"))
        self.CourseSelection.topLevelItem(0).child(0).setText(0, _translate("stuhome", "选择课程"))
        self.CourseSelection.topLevelItem(0).child(1).setText(0, _translate("stuhome", "选退课程"))
        self.CourseSelection.topLevelItem(0).child(2).setText(0, _translate("stuhome", "显示课表"))
        self.CourseSelection.setSortingEnabled(__sortingEnabled)
        self.label_3.setText(_translate("stuhome", "-------------------------"))
        self.label_2.setText(_translate("stuhome", "-------------------------"))
        self.SystemSet_2.headerItem().setText(0, _translate("stuhome", "教师系统"))
        __sortingEnabled = self.SystemSet_2.isSortingEnabled()
        self.SystemSet_2.setSortingEnabled(False)
        self.SystemSet_2.topLevelItem(0).setText(0, _translate("stuhome", "系统管理"))
        self.SystemSet_2.topLevelItem(0).child(0).setText(0, _translate("stuhome", "退出系统"))
        self.SystemSet_2.setSortingEnabled(__sortingEnabled)
        self.ScoreManager_2.headerItem().setText(0, _translate("stuhome", "成绩系统"))
        __sortingEnabled = self.ScoreManager_2.isSortingEnabled()
        self.ScoreManager_2.setSortingEnabled(False)
        self.ScoreManager_2.topLevelItem(0).setText(0, _translate("stuhome", "成绩管理"))
        self.ScoreManager_2.topLevelItem(0).child(0).setText(0, _translate("stuhome", "学生成绩"))
        self.ScoreManager_2.setSortingEnabled(__sortingEnabled)
        self.CourseSelection_2.headerItem().setText(0, _translate("stuhome", "选课系统"))
        __sortingEnabled = self.CourseSelection_2.isSortingEnabled()
        self.CourseSelection_2.setSortingEnabled(False)
        self.CourseSelection_2.topLevelItem(0).setText(0, _translate("stuhome", "选课管理"))
        self.CourseSelection_2.topLevelItem(0).child(0).setText(0, _translate("stuhome", "开设课程"))
        self.CourseSelection_2.topLevelItem(0).child(1).setText(0, _translate("stuhome", "显示课程"))
        self.CourseSelection_2.setSortingEnabled(__sortingEnabled)
        self.label_17.setText(_translate("stuhome", "-------------------------"))
        self.label_18.setText(_translate("stuhome", "-------------------------"))
        self.SystemSet_3.headerItem().setText(0, _translate("stuhome", "管理员系统"))
        __sortingEnabled = self.SystemSet_3.isSortingEnabled()
        self.SystemSet_3.setSortingEnabled(False)
        self.SystemSet_3.topLevelItem(0).setText(0, _translate("stuhome", "系统管理"))
        self.SystemSet_3.topLevelItem(0).child(0).setText(0, _translate("stuhome", "退出系统"))
        self.SystemSet_3.setSortingEnabled(__sortingEnabled)
        self.ScoreManager_3.headerItem().setText(0, _translate("stuhome", "成绩系统"))
        __sortingEnabled = self.ScoreManager_3.isSortingEnabled()
        self.ScoreManager_3.setSortingEnabled(False)
        self.ScoreManager_3.topLevelItem(0).setText(0, _translate("stuhome", "成绩管理"))
        self.ScoreManager_3.topLevelItem(0).child(0).setText(0, _translate("stuhome", "成绩管理"))
        self.ScoreManager_3.topLevelItem(0).child(1).setText(0, _translate("stuhome", "成绩导入"))
        self.ScoreManager_3.setSortingEnabled(__sortingEnabled)
        self.CourseSelection_3.headerItem().setText(0, _translate("stuhome", "课程系统"))
        __sortingEnabled = self.CourseSelection_3.isSortingEnabled()
        self.CourseSelection_3.setSortingEnabled(False)
        self.CourseSelection_3.topLevelItem(0).setText(0, _translate("stuhome", "课程管理"))
        self.CourseSelection_3.topLevelItem(0).child(0).setText(0, _translate("stuhome", "课程审批"))
        self.CourseSelection_3.topLevelItem(0).child(1).setText(0, _translate("stuhome", "课程删除"))
        self.CourseSelection_3.topLevelItem(0).child(2).setText(0, _translate("stuhome", "课程总览"))
        self.CourseSelection_3.setSortingEnabled(__sortingEnabled)
        self.ScoreManager_4.headerItem().setText(0, _translate("stuhome", "信息系统"))
        __sortingEnabled = self.ScoreManager_4.isSortingEnabled()
        self.ScoreManager_4.setSortingEnabled(False)
        self.ScoreManager_4.topLevelItem(0).setText(0, _translate("stuhome", "学生信息管理"))
        self.ScoreManager_4.topLevelItem(0).child(0).setText(0, _translate("stuhome", "学生信息修改"))
        self.ScoreManager_4.topLevelItem(0).child(1).setText(0, _translate("stuhome", "学生信息导入"))
        self.ScoreManager_4.setSortingEnabled(__sortingEnabled)
        self.label_19.setText(_translate("stuhome", "-------------------------"))
        self.label_20.setText(_translate("stuhome", "-------------------------"))
        self.label_21.setText(_translate("stuhome", "-------------------------"))
import home_rc
